services:
  library_back_service:
    container_name: "library_back"
    build:
      context: .
    ports:
      - "8888:8000"
    networks:
      - libraryNetwork
    env_file:
      - .env
  celery_service:
    container_name: "celery_worker"
    build:
      context: .
    networks:
      - libraryNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

networks:
  libraryNetwork:
    external: true